### ISSUE TITLE
catmaid_rename_neuron do longer works

### ISSUE THREAD

**Issue by alexanderbates** [jefferis/rcatmaid#104]
The example 
```# n=get_neuron_name(27296) this is in the help, but actual function below
n=catmaid_get_neuronnames(27296)
catmaid_rename_neuron(skids=27296, names=n)
```
Does not work.

**Comment by alexanderbates** [comment]
Ah sorry, I got confused with which CATMAID I was logged into (v14-seg). Though, I do seem to find that some skids I can't name right now e.g. `370310146` in v14-seg, maybe it's not accessible immediately after upload? But I can annotate it
```Error in catmaid_fetch(path, body = post_data, include_headers = F, conn = conn,  : 
  Not Found (HTTP 404).```

**Comment by jefferis** [comment]
@alexanderbates my conclusion was that this works ok. Is that yours?

**Comment by jefferis** [comment]
Closing as assume ok.
