### ISSUE TITLE
Test cases failing when running command devtools::test()

### ISSUE THREAD

**Issue by SridharJagannathan** [jefferis/rcatmaid#111]
### Scenario:
Run the command devtools::test()
(This is replicable in both the mac and linux machines)

### Results:
Testing catmaid
✔ |  OK F W S | Context
✖ |   0 3     | catmaid annotation queries [1.4 s]
───────────────────────────────────────────────────────────────────────test-annotation.R:9: failure: catmaid_get_annotations_for_skeletons
n1 <- catmaid_get_annotations_for_skeletons(skids = c(10418394)) inherits from `list` not `data.frame`.

test-annotation.R:11: failure: catmaid_get_annotations_for_skeletons
... <- NULL inherits from `list` not `data.frame`.

test-annotation.R:12: failure: catmaid_get_annotations_for_skeletons
rbind(n1, n2) not equal to `n12`.
names for current but not for target
Attributes: < names for target but not for current >
Attributes: < Length mismatch: comparison on first 0 components >
Length mismatch: comparison on first 4 components
Component 2: Modes: numeric, NULL
Component 2: target is numeric, current is NULL
───────────────────────────────────────────────────────────────────────✖ |  15 1     | catmaid login and get/post [0.8 s]
───────────────────────────────────────────────────────────────────────test-connections.R:44: failure: can get and post data
sort(names(neuronnames)) not equal to c("10418394", "4453485").
Lengths differ: 0 is not 2
───────────────────────────────────────────────────────────────────────✖ |   7 3     | catmaid metadata queries [4.4 s]
───────────────────────────────────────────────────────────────────────test-fetch.R:9: failure: catmaid_get_neuronnames
catmaid_get_neuronnames(skids = c(4453485, 10418394)) not equal to `baseline`.
2/2 mismatches
x[1]: NA
y[1]: "IPC 4 left"

x[2]: NA
y[2]: "DH44 1 left"

test-fetch.R:16: failure: catmaid_get_neuronnames with duplicates / NAs
catmaid_get_neuronnames(skids = sk) not equal to `baseline`.
2/3 mismatches
x[1]: NA
y[1]: "IPC 4 left"

x[2]: NA
y[2]: "DH44 1 left"

test-fetch.R:17: failure: catmaid_get_neuronnames with duplicates / NAs
catmaid_get_neuronnames(skids = rep(sk, 2))[1:3] not equal to `baseline`.
2/3 mismatches
x[1]: NA
y[1]: "IPC 4 left"

x[2]: NA
y[2]: "DH44 1 left"
───────────────────────────────────────────────────────────────────────✖ |   1 1     | catmaid neuron queries [0.2 s]
───────────────────────────────────────────────────────────────────────test-fetch.R:44: error: read.neuron(s).catmaid and connectors
no valid nodes for skid:10418394
1: expect_is(n <- read.neuron.catmaid(pid = 1, skid = 10418394, conn = conn), "neuron") at /home/sri/dev/R/rcatmaid/tests/testthat/test-fetch.R:44
2: quasi_label(enquo(object), label, arg = "object")
3: eval_bare(get_expr(quo), get_env(quo))
4: read.neuron.catmaid(pid = 1, skid = 10418394, conn = conn)
5: stop("no valid nodes for skid:", skid) at /home/sri/dev/R/rcatmaid/R/catmaid_nat.R:33
───────────────────────────────────────────────────────────────────────✔ |   7       | nat [0.4 s]
✔ |  14       | plot3d
✔ |   2       | catmaid_selection
✖ |   0 1 1   | test-skeleton.R [1.4 s]
───────────────────────────────────────────────────────────────────────test-skeleton.R:9: warning: 
Assumed you want a complete annotation but found no matches for query "annotation:^ORN PNs$"!

test-skeleton.R:10: error: 
subscript out of bounds
1: expect_is(nc <- catmaid_get_node_count(sk), "integer") at /home/sri/dev/R/rcatmaid/tests/testthat/test-skeleton.R:10
2: quasi_label(enquo(object), label, arg = "object")
3: eval_bare(get_expr(quo), get_env(quo))
4: catmaid_get_node_count(sk)
5: catmaid_get_review_status(good_skids, pid = pid, conn = conn, raw = FALSE, ...) at /home/sri/dev/R/rcatmaid/R/catmaid_skeleton.R:650
6: list2df(res, cols = c("total", "reviewed")) at /home/sri/dev/R/rcatmaid/R/catmaid_metadata.R:364
7: sapply(x, "[[", colidx) at /home/sri/dev/R/rcatmaid/R/catmaid_skeleton.R:70
8: lapply(X = X, FUN = FUN, ...)
───────────────────────────────────────────────────────────────────────✔ |  13   3   | process skid specifications [15.3 s]
───────────────────────────────────────────────────────────────────────test-skids.R:20: warning: process skid queries
No matches for query "annotation:^ORN PNs$"!

test-skids.R:26: warning: process skid queries
Assumed you want a complete annotation but found no matches for query "annotation:^ORN PNs$"!

test-skids.R:26: warning: process skid queries
No matches for query "annotation:^ORN PNs$"!
───────────────────────────────────────────────────────────────────────✔ |   6       | catmaid stats [0.3 s]
✖ |   3 1     | treenode queries [0.4 s]
───────────────────────────────────────────────────────────────────────
test-treenodes.R:8: error: catmaid_get_treenode_table
There are no tree nodes for this skeleton id
1: expect_is(tnt <- catmaid_get_treenode_table(10418394), "data.frame") at /home/sri/dev/R/rcatmaid/tests/testthat/test-treenodes.R:8
2: quasi_label(enquo(object), label, arg = "object")
3: eval_bare(get_expr(quo), get_env(quo))
4: catmaid_get_treenode_table(10418394)
5: stop("There are no tree nodes for this skeleton id") at /home/sri/dev/R/rcatmaid/R/catmaid_skeleton.R:359
───────────────────────────────────────────────────────────────────────══ Terminating early ═══════════════════════════════════════════════════════════════════════Too many failures

**Comment by jefferis** [comment]
The test cases are written against the Drosophila L1 larva server. Therefore they cannot run against the adult server to which you have access. I have been considering for some time switching the tests to run against a publicly accessible server, https://l1em.catmaid.virtualflybrain.org. This will contain some but not all of the neurons/annotations referenced in the existing tests. If you would like to try converting the tests, then a PR would be welcome, although it might be easier if you could look at the results returned by the existing L1 server.
