### ISSUE TITLE
Put url into InputFileName?

### ISSUE THREAD

**Issue by jefferis** [jefferis/rcatmaid#120]
`nat::write.neurons` relies on the contents of the `InputFileName` field of neurons to define a default output file name. It would be good if `read.neuron.catmaid` defined this field. Maybe we should just put the source catmaid url in there.

```r
> orns=read.neurons.catmaid("ORN")
> write.neurons(orns, dir='orns.zip')
Error in basename(n$InputFileName) : a character vector argument expected
```

Also `nat::write.neurons` should be more careful in its test for `InputFileName`.

**Comment by jefferis** [comment]
```r
n=nat::as.neuron(swc, origin=soma_id_in_neuron, skid=skid, InputFileName=url)
```
you can get the URL from the CATMAID `res` object.

https://github.com/jefferis/rcatmaid/blob/96c458212042a96ae7908742d91cef7a1a7a1ebc/R/catmaid_nat.R#L31-L40

**Comment by jefferis** [comment]
@SridharJagannathan another one to take a look at.

**Comment by SridharJagannathan** [comment]
@jefferis Are you sure about getting the `url` from the `res` object. I tried the following:
`orns=read.neurons.catmaid("annotation:^ORN$", OmitFailures = T, .progress='text')` and further I had a breakpoint and checked the  `res` object and it seems it doesn't contain any field `url`

**Comment by jefferis** [comment]
It should be one of the attributes. I can’t remember if you neeed to tell catmaid_fetch to include the header fields of the result.

**Comment by jefferis** [comment]
PS in case this wasn’t clear this has to be in read.neuron.catmaid ie the version  for just one neuron

**Comment by jefferis** [comment]
OK so we can close this now. We didn't use the URL, just the skid.
