### ISSUE TITLE
OmitFailures argument for catmaid_get_treenodes_detail()

### ISSUE THREAD

**Issue by mmc46** [jefferis/rcatmaid#125]
Running  catmaid_get_treenodes_detail() for a large number of skids, getting:

```# Error: lexical error: malformed number, a digit is required after the decimal point.
# [[44507812, 18808341, 455047.0
#   (right here) ------^```

Could a `OmitFailures` argument be added?

**Comment by jefferis** [comment]
Can you give the query?

**Comment by jefferis** [comment]
I can recapitulate. However AFAICS this failure was just about the size of the query being too large. In particular if I break the query into batches of a few hundred neurons then each individual batch works fine. I don't currently have a built-in way to chunk the queries, but there are various ways this could be achieved. Using `by` or a `dplyr` `group_by` after making a `chunk` column are possible ways.

```r
catmaid_get_treenodes_detail_chunked <- function(x, chunksize=300, chunkstoread=NULL, ...) {
  nchunks=ceiling(length(x)/chunksize)
  chunks=rep(seq_len(nchunks), rep(chunksize, nchunks))[seq_along(x)]
  
  l=list()
  if(is.null(chunkstoread)) chunkstoread=seq_len(nchunks)
  pb <- progress::progress_bar$new(total = length(x),
                                   format = "  :current/:total [:bar]  eta: :eta",
                                   show_after=1)
  
  for(i in chunkstoread) {
    pb$tick(len = sum(chunks==i))
    l[[length(l)+1]]=catmaid_get_treenodes_detail(skids=x[chunks==i], ...)
  }
  dplyr::bind_rows(l)
}
```

Which could be called like so:

```r
td=catmaid_get_treenodes_detail_chunked(sample(names(fulln)[1:300]), chunksize = 10)
```

**Comment by jefferis** [comment]
The default `chunksize=300` should be fine, I used a smaller chunksize for demonstration.

**Comment by jefferis** [comment]
We could implement this but would be a little bit fiddly to chunk over `skids`, tree node ids, `labels` and combinations thereof.

**Comment by jefferis** [comment]
Have put this as an example in 18e0ffd3fcc64163528483c6dbfaa2865654ffce

**Comment by mmc46** [comment]
I can just use the chunked version you posted above for skids, thanks.
