### ISSUE TITLE
url for retrieving annotated neurons has changed

### ISSUE THREAD

**Issue by jefferis** [jefferis/rcatmaid#32]
See https://github.com/schlegelp/CATMAID-to-Blender/commit/affa8ea2077dd2a24e03e966614f6ff1211844cc?diff=unified#diff-44c6fcbc2c55bf80a53135d9e4e81322
v3.9.4

```
"/neuron/query-by-annotations"-> "/annotations/query-targets"
```
also the post data has changed

```
#annotation_post = {'neuron_query_by_annotation': annotation_id, 'display_start': 0, 'display_length':500}
annotation_post = {'annotated_with0': annotation_id, 'rangey_start': 0, 'range_length':500, 'with_annotations':False}
```

**Comment by jefferis** [comment]
Also `neuron_query_by_name` => `name` for query by name post data

**Comment by jefferis** [comment]
@alexanderbates maybe you could check the fix works for you.

**Comment by alexanderbates** [comment]
The fix works :)
