### ISSUE TITLE
404 Error: catmaid_get_connected

### ISSUE THREAD

**Issue by alexanderbates** [jefferis/rcatmaid#34]
When I try to use catmaid_get_connected, I get the error:

Error in catmaid_fetch(path, connectivity_post, include_headers = F, ...) : 
  client error: (404) Not Found

**Comment by jefferis** [comment]
Thanks. Looks like another API change. I'll try to roll out a fix later.

**Comment by jefferis** [comment]
See https://github.com/catmaid/CATMAID/commit/fd0e96d28165d8cfee0e5398d40b287586fb46b9
