### ISSUE TITLE
XXX header in 1st column of connector data.frame

### ISSUE THREAD

**Issue by zhihaozheng** [jefferis/rcatmaid#42]
First column of the connector data.frame for neuron objects downloaded from CATMAID has variable name 'XXX' (unknown identifier). Also in 'connectors' documentation. I believe the number is 'treenode id'. If it is an outgoing connectors, the number is pre-synaptic treenode id; for incoming connectors, it is post-synaptic treenode id.

**Comment by jefferis** [comment]
Thanks @zhihaozheng. I've been meaning to fix that when I could check what it actually was. Can you give me some evidence that it is indeed the `treenode id` e.g. catmaid source, example results that you have cross checked etc. Many thanks, Greg.

**Comment by jefferis** [comment]
Thanks @zhihaozheng for sending more info privately. Just to clarify, is it your understanding that the  `treenode id` always refers to the **current** skeleton rather than the partner?

**Comment by zhihaozheng** [comment]
Right. Say test_kc[[1]] is a neuron object. I used this one line code to test it. 

all(test_kc[[1]]$connectors$XXX %in% test_kc[[1]]$d$PointNo)

Zhihao

**Comment by jefferis** [comment]
Perfect. Thanks for confirming.
