### ISSUE TITLE
suggest a catmaid_get_connector_info function

### ISSUE THREAD

**Issue by zhihaozheng** [jefferis/rcatmaid#52]
There is a CATMAID [connector_info](https://github.com/catmaid/CATMAID/blob/7628b8787427d23662212ca8b8ab73c23b4fbbc1/django/applications/catmaid/urls.py#L164) API that I use quite often. It returns connector info for given pre_skids and post_skids. One can get these with existing functions in the package but it is nice to access it directly. Andrew had test coverage [here](https://github.com/catmaid/CATMAID/commit/e07e5163652f0ca22ca8e97b632c5a078271dd20). I just want to suggest it here so if you think it is useful enough you can add the function. Or I am happy to fork the code and send a Pull request with the function and relevant documentations if you like.

Here is a copy of the function from my script.
`catmaid_get_connector_info <- function(pre_skids, post_skids, pid=1, conn=NULL, raw=FALSE, ...) {
  path=paste("", pid, "connector","pre-post-info",sep="/")
  pre=as.list(pre_skids)
  names(pre)=sprintf("pre[%d]", seq(from=0, along.with=pre_skids))
  post=as.list(post_skids)
  names(post)=sprintf("post[%d]", seq(from=0, along.with=post_skids))
  post_data = c(pre, post)
  conns=catmaid_fetch(path, body=post_data, conn=conn, ...)
  
  if(raw) return(conns)
  
  df=do.call(rbind, conns)
  colnames(df)=c("connector_id", "connector_xyz", "pre_node_id", "pre_skid", "pre_confidence", "pre_creator", "pre_node_xyz", 
                  "post_node_id", "post_skid", "post_confidence", "post_creator", "post_node_xyz")
  df
}`

**Comment by jefferis** [comment]
Thanks for the suggestion, Zhihao. Why don't you make a pull request. The fn below looks good. If you look at most of the other functions that accept multiple skids they insert a call to the catmaid_skids function which allows specification by name or annotation, so you could try adding that. Best, Greg.
