### ISSUE TITLE
CATMAID API change for the endpoint of catmaid_get_connectors_between

### ISSUE THREAD

**Issue by zhihaozheng** [jefferis/rcatmaid#56]
https://github.com/jefferis/rcatmaid/blob/afe411d293d15e838e91bba40e6591a4b7d66bd8/R/catmaid_skeleton.R#L333

Please refer to: https://github.com/catmaid/CATMAID/releases/tag/2016.08.09

> POST /{project_id}/connector/info:
> This endpoint replaces the /{project_id}/connector/pre-post-infos endpoint

**Comment by jefferis** [comment]
Thanks @zhihaozheng. Is is just the path that has changed? Maybe you could do a PR.

**Comment by zhihaozheng** [comment]
Yes, will do PR. `pre` and `post` now become [optional parameters](https://github.com/catmaid/CATMAID/blob/b47e2f6bb8e1d040e50a2348272a4fdadccd2f75/django/applications/catmaid/static/libs/catmaid/models/connectors.js#L185), and other optional parameters are `cids` (connectorIds) and `skids` (skeletonIds). So for example one could just supply `pre` and get all the presynaptic-related connectors. But I think other options are already covered by other functions in the package. So I will just change the path, test it, and add a bit to make `pre` and `post` optional.

**Comment by jefferis** [comment]
Actually Zhihao I happen to need this now, so I'm going to push a quick fix. Maybe you can review. Best, Greg.
