### ISSUE TITLE
Catmaid_get_conector_table misbehaving 

### ISSUE THREAD

**Issue by alexanderbates** [jefferis/rcatmaid#66]
404 error in larval catmaid with catmaid_fetch:
` c = catmaid_get_connector_table("4119387")
Error in catmaid_fetch(path = paste0("/", pid, "/connector/table/list"),  : 
  Not Found (HTTP 404).`

**Comment by jefferis** [comment]
Yes, API changes are a bit of a pain. There is a provisional fix on https://github.com/jefferis/rcatmaid/compare/fix/connector-table-v2016.10.18

You can try it out with:

```r
devtools::install_github("jefferis/rcatmaid@fix/connector-table-v2016.10.18")
```

Testing welcome before I merge to master as well as views on what to do about the change in return format.

**Comment by alexanderbates** [comment]
"2016.09.01-107-g146bc78"

**Comment by jefferis** [comment]
have brought API change point forward (https://github.com/jefferis/rcatmaid/pull/67/commits/ba06c885212f23a100894b1c12aaf34b824ecfa3) so larval server should work as well now.

**Comment by jefferis** [comment]
I am a little puzzled about the change in return values of the underlying API call. It no longer returns the partner skid, but I am not 100% sure that it did in the past. I have now added some coded (controlled by an additional argument that will fetch the partner skid information by calling `catmaid_get_connectors`)
