### ISSUE TITLE
catmaid_get_treenode_table doesn't return type column

### ISSUE THREAD

**Issue by mmc46** [jefferis/rcatmaid#75]
```
tnt=catmaid_get_treenode_table(487780)
str(tnt)
'data.frame':	3319 obs. of  10 variables:
 $ id           : int  2570502 2574274 2628489 3971731 3971732 3971736 3971738 3971741 3971754 3971785 ...
 $ parent_id    : int  3997071 NA 3997143 2574274 3971731 3971732 3971736 3971738 3971741 3971741 ...
 $ confidence   : int  5 5 5 5 5 5 5 5 5 5 ...
 $ x            : num  426403 430010 425890 430031 430027 ...
 $ y            : num  235318 237901 236087 237827 237798 ...
 $ z            : num  132650 129150 132335 129115 129080 ...
 $ r            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
 $ user_id      : int  75 75 75 92 92 92 92 92 92 92 ...
 $ last_modified: num  1.47e+09 1.46e+09 1.47e+09 1.47e+09 1.47e+09 ...
 $ reviewer_id  : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
 - attr(*, "tags")='data.frame':	99 obs. of  2 variables:
  ..$ id : int  3972006 3972133 3972389 3972507 3972975 3973702 3973940 3975345 3976049 3976069 ...
  ..$ tag: chr  "uncertain continuation" "uncertain end" "uncertain end" "ends" ...
 - attr(*, "reviews")='data.frame':	0 obs. of  2 variables:
  ..$ id         : int 
  ..$ reviewer_id: int 
```

But according to doc it should
http://jefferis.github.io/rcatmaid/reference/catmaid_get_treenode_table.html

**Comment by jefferis** [comment]
Thanks. That seems to be a doc error – I don't see any sign of a type column in the results.

It may have disappeared around this commit:

https://github.com/jefferis/rcatmaid/commit/f30a6153384bf72e56c7ee09258891b82b703ca5



On 16 Feb 2017, at 16:35, Marta Costa <notifications@github.com> wrote:

> tnt=catmaid_get_treenode_table(487780)
> str(tnt)
> 'data.frame':	3319 obs. of  10 variables:
>  $ id           : int  2570502 2574274 2628489 3971731 3971732 3971736 3971738 3971741 3971754 3971785 ...
>  $ parent_id    : int  3997071 NA 3997143 2574274 3971731 3971732 3971736 3971738 3971741 3971741 ...
>  $ confidence   : int  5 5 5 5 5 5 5 5 5 5 ...
>  $ x            : num  426403 430010 425890 430031 430027 ...
>  $ y            : num  235318 237901 236087 237827 237798 ...
>  $ z            : num  132650 129150 132335 129115 129080 ...
>  $ r            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
>  $ user_id      : int  75 75 75 92 92 92 92 92 92 92 ...
>  $ last_modified: num  1.47e+09 1.46e+09 1.47e+09 1.47e+09 1.47e+09 ...
>  $ reviewer_id  : Factor w/ 0 levels: NA NA NA NA NA NA NA NA NA NA ...
>  - attr(*, "tags")='data.frame':	99 obs. of  2 variables:
>   ..$ id : int  3972006 3972133 3972389 3972507 3972975 3973702 3973940 3975345 3976049 3976069 ...
>   ..$ tag: chr  "uncertain continuation" "uncertain end" "uncertain end" "ends" ...
>  - attr(*, "reviews")='data.frame':	0 obs. of  2 variables:
>   ..$ id         : int 
>   ..$ reviewer_id: int 
> But according to doc it should
> http://jefferis.github.io/rcatmaid/reference/catmaid_get_treenode_table.html
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Gregory Jefferis, PhD
Division of Neurobiology
MRC Laboratory of Molecular Biology
Francis Crick Avenue
Cambridge Biomedical Campus
Cambridge, CB2 OQH, UK

http://www2.mrc-lmb.cam.ac.uk/group-leaders/h-to-m/g-jefferis
http://jefferislab.org
http://flybrain.stanford.edu

**Comment by mmc46** [comment]
There is a type column in the CATMAID treenode table.
